This one did worse than my GradientBoost one, don't look at it

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingClassifier
import numpy as np

In [2]:
dtest = pd.read_csv("train.csv")

ftest = pd.read_csv("test.csv")

dtest.drop("Name", axis=1, inplace = True)

In [3]:
y = dtest.Transported
features = ['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age', 'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']

X = dtest[features]
X2 = ftest[features]

X_train, X_valid, y_train, y_valid = train_test_split(X,y)

object_cols = [col for col in X_train.columns if X_train[col].dtype == "object"]

In [6]:
OHcols = ["CryoSleep", "VIP", "Destination", "HomePlanet"]

cols2 = ["Cabin", "PassengerId"]
dtest2 = dtest[cols2]
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
#Up here is changing the amount of rows
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X_train[OHcols]))
OH_cols_valid = pd.DataFrame(OH_encoder.transform(X_valid[OHcols]))
OH_cols_final = pd.DataFrame(OH_encoder.fit_transform(X2[OHcols]))

# Putting index bacl
OH_cols_train.index = X_train.index
OH_cols_valid.index = X_valid.index
OH_cols_final.index = X2.index

# Removing previous columns
num_X_train = X_train.drop(object_cols, axis=1)
num_X_valid = X_valid.drop(object_cols, axis=1)
num_final = X2.drop(object_cols, axis = 1)

# Adding to other columns
OH_X_train = pd.concat([num_X_train, OH_cols_train], axis=1)
OH_X_valid = pd.concat([num_X_valid, OH_cols_valid], axis=1)
OH_X_final = pd.concat([num_final, OH_cols_final], axis=1)
# Imputing the numerical columns
my_imputer = SimpleImputer()
Mid_X_train = pd.DataFrame(my_imputer.fit_transform(OH_X_train))
Mid_X_valid = pd.DataFrame(my_imputer.transform(OH_X_valid))
Mid_final = pd.DataFrame(my_imputer.transform(OH_X_final))

# Imputation removed column names; put them back
Mid_X_train.columns = OH_X_train.columns
Mid_X_valid.columns = OH_X_valid.columns
Mid_final.columns = OH_X_final.columns

/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(

In [16]:
Mid_X_train['Cabin']= X_train['Cabin']
Mid_X_valid['Cabin']= X_valid['Cabin']
Mid_final['Cabin']= X2['Cabin']

In [17]:
Mid_X_train

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,0,1,2,3,...,5,6,7,8,9,10,11,12,13,Cabin
0,19.0,64.0,0.0,453.0,174.0,6.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,B/0/P
1,51.0,0.0,0.0,0.0,0.0,880.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,F/0/S
2,30.0,558.0,4.0,0.0,175.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,A/0/S
3,8.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,NaN
4,21.0,1946.0,37.0,0.0,0.0,24.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6514,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN
6515,23.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,F/1315/S
6516,19.0,0.0,1342.0,0.0,152.0,556.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,E/457/S
6517,31.0,3.0,0.0,0.0,747.0,43.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,F/1430/P
6518,19.0,150.0,605.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,E/438/P

https://www.kaggle.com/code/samuelcortinhas/spaceship-titanic-a-complete-guide

In [18]:
# Replace NaN's with outliers for now (so we can split feature)
Mid_X_train['Cabin'].fillna('Z/9999/Z', inplace=True)
Mid_X_valid['Cabin'].fillna('Z/9999/Z', inplace=True)
Mid_final['Cabin'].fillna('Z/9999/Z', inplace=True)

# New features - training set
Mid_X_train['Cabin_deck'] = Mid_X_train['Cabin'].apply(lambda x: x.split('/')[0])
Mid_X_train['Cabin_number'] = Mid_X_train['Cabin'].apply(lambda x: x.split('/')[1]).astype(int)
Mid_X_train['Cabin_side'] = Mid_X_train['Cabin'].apply(lambda x: x.split('/')[2])

# New features - test set
Mid_X_valid['Cabin_deck'] = Mid_X_valid['Cabin'].apply(lambda x: x.split('/')[0])
Mid_X_valid['Cabin_number'] = Mid_X_valid['Cabin'].apply(lambda x: x.split('/')[1]).astype(int)
Mid_X_valid['Cabin_side'] = Mid_X_valid['Cabin'].apply(lambda x: x.split('/')[2])

Mid_final['Cabin_deck'] = Mid_final['Cabin'].apply(lambda x: x.split('/')[0])
Mid_final['Cabin_number'] = Mid_final['Cabin'].apply(lambda x: x.split('/')[1]).astype(int)
Mid_final['Cabin_side'] = Mid_final['Cabin'].apply(lambda x: x.split('/')[2])

# Put Nan's back in (we will fill these later)
Mid_X_train.loc[Mid_X_train['Cabin_deck']=='Z', 'Cabin_deck']=np.nan
Mid_X_train.loc[Mid_X_train['Cabin_number']==9999, 'Cabin_number']=np.nan
Mid_X_train.loc[Mid_X_train['Cabin_side']=='Z', 'Cabin_side']=np.nan
Mid_X_valid.loc[Mid_X_valid['Cabin_deck']=='Z', 'Cabin_deck']=np.nan
Mid_X_valid.loc[Mid_X_valid['Cabin_number']==9999, 'Cabin_number']=np.nan
Mid_X_valid.loc[Mid_X_valid['Cabin_side']=='Z', 'Cabin_side']=np.nan

Mid_final.loc[Mid_final['Cabin_deck']=='Z', 'Cabin_deck']=np.nan
Mid_final.loc[Mid_final['Cabin_number']==9999, 'Cabin_number']=np.nan
Mid_final.loc[Mid_final['Cabin_side']=='Z', 'Cabin_side']=np.nan

# Drop Cabin (we don't need it anymore)
Mid_X_train.drop('Cabin', axis=1, inplace=True)
Mid_X_valid.drop('Cabin', axis=1, inplace=True)
Mid_final.drop('Cabin', axis=1, inplace=True)

In [19]:
Mid_X_train

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,0,1,2,3,...,7,8,9,10,11,12,13,Cabin_deck,Cabin_number,Cabin_side
0,19.0,64.0,0.0,453.0,174.0,6.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,B,0.0,P
1,51.0,0.0,0.0,0.0,0.0,880.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,F,0.0,S
2,30.0,558.0,4.0,0.0,175.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,A,0.0,S
3,8.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
4,21.0,1946.0,37.0,0.0,0.0,24.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6514,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN
6515,23.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,F,1315.0,S
6516,19.0,0.0,1342.0,0.0,152.0,556.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,E,457.0,S
6517,31.0,3.0,0.0,0.0,747.0,43.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,F,1430.0,P
6518,19.0,150.0,605.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,E,438.0,P

In [20]:
OHcols2 = ["Cabin_deck", "Cabin_side"]

OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
#Up here is changing the amount of rows
OH_cols_train2 = pd.DataFrame(OH_encoder.fit_transform(Mid_X_train[OHcols2]))
OH_cols_valid2 = pd.DataFrame(OH_encoder.transform(Mid_X_valid[OHcols2]))
OH_cols_final2 = pd.DataFrame(OH_encoder.fit_transform(Mid_final[OHcols2]))

# Putting index bacl
OH_cols_train.index = Mid_X_train.index
OH_cols_valid.index = Mid_X_valid.index
OH_cols_final.index = Mid_final.index

object_cols2 = [col for col in Mid_X_train.columns if Mid_X_train[col].dtype == "object"]

# Removing previous columns
num_X_train = Mid_X_train.drop(object_cols2, axis=1)
num_X_valid = Mid_X_valid.drop(object_cols2, axis=1)
num_final = Mid_final.drop(object_cols2, axis = 1)

# Adding to other columns
OH_X_train2 = pd.concat([num_X_train, OH_cols_train2], axis=1)
OH_X_valid2 = pd.concat([num_X_valid, OH_cols_valid2], axis=1)
OH_X_final2 = pd.concat([num_final, OH_cols_final2], axis=1)

# Imputing the numerical columns
my_imputer = SimpleImputer()
Mid_X_train = pd.DataFrame(my_imputer.fit_transform(OH_X_train2))
Mid_X_valid = pd.DataFrame(my_imputer.transform(OH_X_valid2))
Mid_final = pd.DataFrame(my_imputer.transform(OH_X_final2))

# Imputation removed column names; put them back
Mid_X_train.columns = OH_X_train2.columns
Mid_X_valid.columns = OH_X_valid2.columns
Mid_final.columns = OH_X_final2.columns

/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(

In [22]:
model = GradientBoostingClassifier()
model.fit(Mid_X_train, y_train)
train_final = pd.concat([Mid_X_valid, Mid_X_train])
y_final = pd.concat([y_valid, y_train])
model.predict(train_final)
y_final.isna().sum()

model_final = GradientBoostingClassifier(random_state = 1, max_depth = 4)
model_final.fit(train_final, y_final)
preds = model_final.predict(Mid_final)

output = pd.DataFrame({"PassengerId": ftest.PassengerId, "Transported": preds})
output.to_csv('submission6.csv', index = False)

/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/sarahbraverman/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(